### ISSUE TITLE
discontinuityStarts

### ISSUE THREAD

**Issue by Capelinha** [matschik/vodtwitch#1]
Hi, I tried to download the vod and the 'discontinuidadeStarts' pointed to the last part of m3u8. I didn't understand why the download only starts from the 'discontinuityStarts'. I'm new to the subject of downloading streams

**Comment by matschik** [comment]
Hello ! Can you give me the vod ID ? You can send to me by email if you want: mathieu.schimmerling@protonmail.com
Can you also copy paste the error ? Thanks :)

**Comment by Capelinha** [comment]
https://www.twitch.tv/videos/862200099

Progress jumps to 100% as soon as it starts

**Comment by matschik** [comment]
I fixed the problem, you can try it by updating to the last version: vodtwitch@1.1.2
Tell me if it's working until the vod is completely downloaded :)

**Comment by Capelinha** [comment]
it worked perfectly, thanks. Seriously that twitch discontinued the api yesterday?

**Comment by matschik** [comment]
I was not using playlist `discountinuity` really well. I think I found a way to use this property correctly. I don't think that's perfect: https://github.com/matschik/vodtwitch/commit/82b15d4f2c4cffc533781dc6fff3441f5ca5d6a6

This was also an opportunity to readapt vod credentials fetching because Twitch is using a new api endpoint for vod credentials: https://github.com/matschik/vodtwitch/commit/df327727b642d0ee1e3f5b4778805b1ae63a496a
`vodtwitch` would not work without this fix suddenly from one day to the next.

Thanks a lot for reporting this issue, i'm closing it :)
